FROM ghcr.io/cross-rs/x86_64-unknown-linux-gnu:latest

RUN apt-get update && apt-get install -y \
    libavformat-dev \
    libavcodec-dev \
    libavutil-dev \
    libswresample-dev \
    libswscale-dev \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

ENV PKG_CONFIG_ALLOW_CROSS=1
